vmec_file: wout_vmec.nc

invessel_build:
  toroidal_angles: [0.0, 22.5, 45.0, 67.5, 90.0]
  poloidal_angles: [0.0, 90.0, 180.0, 270.0, 360.0]
  wall_s: 1.08
  radial_build:
    first_wall:
      thickness_matrix:
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
    breeder:
      thickness_matrix:
        - [80, 40, 20, 40, 80]
        - [50, 40, 30, 30, 50]
        - [30, 30, 25, 30, 30]
        - [50, 30, 30, 40, 50]
        - [80, 40, 20, 40, 80]
    back_wall:
      thickness_matrix:
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
    shield:
      thickness_matrix:
        - [50, 25, 15, 25, 50]
        - [30, 25, 20, 20, 30]
        - [20, 20, 15, 20, 20]
        - [30, 20, 20, 25, 30]
        - [50, 25, 15, 25, 50]
    vacuum_vessel:
      thickness_matrix:
        - [15, 15, 15, 15, 15]
        - [15, 15, 15, 15, 15]
        - [15, 15, 15, 15, 15]
        - [15, 15, 15, 15, 15]
        - [15, 15, 15, 15, 15]
      mat_tag: vac_vessel
  export_cad_to_dagmc: False
  dagmc_filename: dagmc
  export_dir: ''

magnet_coils:
  coils_file: coils.example
  cross_section: [circle, 20.0]
  toroidal_extent: 90.0
  sample_mod: 6
  step_filename: magnet_coils
  export_mesh: True
  mesh_filename: magnet_mesh
  export_dir: ''

source_mesh:
  mesh_size: [11, 81, 61]
  toroidal_extent: 90.0
  filename: source_mesh
  export_dir: ''

dagmc_export:
  skip_imprint: False
  legacy_faceting: True
  filename: dagmc
  export_dir: ''
